### ISSUE TITLE
reset button on tauri app doesnt reset registers (or at least the sp register)

### ISSUE THREAD

**Issue by michaelni678** [ezasm-org/rezasm#43]

**Comment by TrevorBrunette** [comment]
Please provide a better description of the bug next time.

The issue is in App.js that `callCallbacks` is called conditionally since it is in `checkAndHandleProgramCompletion`  -- a solution might be to call `callCallbacks` in the reset function. Make sure to include it as a dependency in the dependency array wherever you put it.
